name: Deploy to cPanel

on:
  push:
    branches:
      - master # We can change this if you prefer a different branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # will try node version 14 first, might be better with later version.

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to cPanel
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          ftp-server: ftp://${{ secrets.FTP_SERVER }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: out/
          server-dir: / # Path to the directory on your serve
