name: Deploy to cPanel

on:
  push:
    branches:
      - master # We can change this if you prefer a different branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # will try node version 14 first, might be better with later version.

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to cPanel
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "out/*"
          target: ${{ secrets.DESTINATION }}
